export const TICKERS_WEBSOCKET_OPEN = 'TICKERS_WEBSOCKET_OPEN'
export const TICKERS_WEBSOCKET_CLOSE = 'TICKERS_WEBSOCKET_CLOSE'
export const TICKERS_WEBSOCKET_MESSAGE = 'TICKERS_WEBSOCKET_MESSAGE'
export const TOGGLE_TICKERS_WEBSOCKET = 'TOGGLE_TICKERS_WEBSOCKET'
export const TRIGGER_SORT = 'TRIGGER_SORT'

export const TRADE_WEBSOCKET_OPEN = 'TRADE_WEBSOCKET_OPEN'
export const TRADE_WEBSOCKET_CLOSE = 'TRADE_WEBSOCKET_CLOSE'
export const TRADE_WEBSOCKET_MESSAGE = 'TRADE_WEBSOCKET_MESSAGE'

export const PING_REQUESTED = 'PING_REQUESTED'
export const PING_SUCCEEDED = 'PING_SUCCEEDED'
export const PING_FAILED = 'PING_FAILED'
